### ISSUE TITLE
database setup - tables/schema and data

### ISSUE THREAD

**Issue by dmoellenbeck** [suadev/microservices-change-data-capture-with-debezium#1]
Could you please add a short description on how to initiate the database setup. I guess it's through EF core migration.

**Comment by suadev** [comment]
@dmoellenbeck, Each service will be created its own database while it's starting for the first time.  The method below ensures that DB is created and run all migrations. I'll add a short description about it, thank you.

```cs
    public static class DbInitilializer
    {
        public static void Migrate<T>(IServiceProvider serviceProvider) where T : DbContext
        {
            using (var scope = serviceProvider.CreateScope())
            {
                var context = scope.ServiceProvider.GetRequiredService<T>();
                context.Database.Migrate();
            }
        }
    }
```

**Comment by dmoellenbeck** [comment]
Thanks, works perfectly now.
